- hosts: localhost
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: ""
        validate_certs: no
        namespace: default
        validate:
          fail_on_error: no
          strict: yes
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition: ""
